name: cetinajero.github.io/cv
title: CV                               # head title tag
url: https://cetinajero.github.io/cv
timezone: America/Chihuahua
permalink: /:categories/:title/

markdown: kramdown
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
