title: CV                               # head title tag
name: Jekyll CV
public-url: https://cetinajero.github.io/cv
logo: /img/me_small.jpg
lang: es_MX
timezone: America/Chihuahua
author: cetinajero
twitter:
  username: cetinajero
social:
  name: cetinajero
  links:
      - https://about.me/cetinajero
      - https://github.com/cetinajero
      - https://twitter.com/cetinajero
      - https://facebook.com/cetinajero
      - https://linkedin.com/in/cetinajero
      - https://plus.google.com/u/0/+EdgarTinajero
permalink: /:categories/:title/

markdown: kramdown
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
