title: CV                               # head title tag
description: Edgar Tinajero's Curriculum Vitae
keywords: cv, curriculum, vitae, curriculum vitae
name: Jekyll CV
theme: null
repository: https://github.com/cetinajero/cv
logo: /img/me_small.jpg
lang: es_MX
timezone: America/Chihuahua
author: cetinajero
twitter:
  username: cetinajero
social:
  name: cetinajero
  links:
      - https://about.me/cetinajero
      - https://github.com/cetinajero
      - https://twitter.com/cetinajero
      - https://facebook.com/cetinajero
      - https://linkedin.com/in/cetinajero
      - https://plus.google.com/u/0/+EdgarTinajero
permalink: /:categories/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      published: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# SEO info
author: Edgar Tinajero

exclude: ["CNAME", "Gemfile", "Gemfile.lock", "Rakefile", "package.json", "LICENSE", "README.md", "vendor"]
